#!/bin/sh /etc/rc.common
START=99
USE_PROCD=0

start() {
  # پاکسازی بقایا در بوت‌های بعدی (به‌دلخواه شما)
  [ -d /root/passwall_tmp ] && rm -rf /root/passwall_tmp
  [ -f /tmp/pw_installer.log ] && rm -f /tmp/pw_installer.log
}

